# Wallpaper daemon
exec-once = swww-daemon

# Notification daemon
exec-once = swaync

# Waybar
exec-once = waybar

# Polkit (needed for GUI auth popups)
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Software rendering fix for VirtualBox (remove on bare metal)
env = LIBGL_ALWAYS_SOFTWARE,1