# ===========================
#   Catppuccin Hyprland
#   by rndmCodeGuy20
# ===========================

source = ~/.config/hypr/conf/colors.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/decorations.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/autostart.conf

# Misc
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo   = true
    disable_splash_rendering = true
    vfr                     = true
}

# Environment variables
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,catppuccin-mocha-dark-cursors
env = GTK_THEME,catppuccin-mocha-standard-blue-dark
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,24